FROM node:20-alpine

# Crear directorio de la app
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install 
# Copiar el resto del código
COPY . .

# Exponer el puerto de la app
EXPOSE 3000

# Comando por defecto para iniciar
CMD ["npm", "start"]
