version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal   # Nombre especial para apuntar al host
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=mi_bd
